# Generated by Django 3.0.10 on 2022-06-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boks', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('rasa', models.CharField(max_length=100)),
                ('plec', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pies_leczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leczenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestr.Leczenie')),
                ('pies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestr.Pies')),
            ],
        ),
        migrations.CreateModel(
            name='Pies_dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestr.Dieta')),
                ('pies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestr.Pies')),
            ],
        ),
        migrations.CreateModel(
            name='Pies_badania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Badania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestr.Badania')),
                ('pies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestr.Pies')),
            ],
        ),
    ]
