# Generated by Django 3.0.10 on 2022-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0002_auto_20220606_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='pies',
            name='wiek',
            field=models.DateField(auto_now=True),
        ),
    ]
