# Generated by Django 3.0.10 on 2022-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestr', '0003_pies_wiek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pies',
            name='wiek',
            field=models.DateField(),
        ),
    ]
